-- Seed the corrected substance catalog (265 substances). ADR-038.
-- Idempotent: upserts by name, then removes any leftover non-catalog substance that
-- nothing references (so a fresh DB / PROD ends with exactly this catalog, and on QA
-- the still-referenced legacy rows survive for the one-off reconcile script). Needs
-- 'cfu' in substance_unit (migration 0013) for the probiotic rows.

insert into substance (name, substance_type, canonical_unit, aliases) values
  ('Bicarbonate', 'electrolyte', 'mg', array['hco3', 'bicarbonaat']::text[]),
  ('Chloride', 'electrolyte', 'mg', array['cl', 'chloor', 'chloride ion']::text[]),
  ('Magnesium Citrate', 'electrolyte', 'mg', array['magnesium salt of citric acid', 'magnesiumcitraat']::text[]),
  ('Magnesium Glycinate', 'electrolyte', 'mg', array['magnesium bisglycinate', 'magnesiumglycinaat', 'magnesiumbisglycinaat']::text[]),
  ('Potassium', 'electrolyte', 'mg', array['k', 'kalium', 'potassium ion']::text[]),
  ('Potassium Citrate', 'electrolyte', 'mg', array['tripotassium citrate', 'kaliumcitraat']::text[]),
  ('Sodium', 'electrolyte', 'mg', array['na', 'natrium', 'sodium ion']::text[]),
  ('Sodium Chloride', 'electrolyte', 'g', array['salt', 'table salt', 'nacl', 'zout', 'keukenzout', 'Himalayazout', 'sea salt', 'Himalayan salt', 'zeezout']::text[]),
  ('Energy', 'energy', 'kcal', array['calories', 'kcal', 'kilocalories', 'calorieën', 'energie', 'kilocalorieën']::text[]),
  ('Added Sugars', 'macronutrient', 'g', array['added sugar', 'free sugars', 'toegevoegde suikers', 'vrije suikers']::text[]),
  ('Alpha-Linolenic Acid', 'macronutrient', 'mg', array['plant omega-3', 'omega-3 ALA', 'alfa-linoleenzuur']::text[]),
  ('Arachidonic Acid', 'macronutrient', 'mg', array['aa', 'ARA', 'omega-6 arachidonic acid', 'arachidonzuur']::text[]),
  ('Beta-Glucan', 'macronutrient', 'g', array['β-glucan', 'oat beta glucan', 'bètaglucaan']::text[]),
  ('Capric Acid', 'macronutrient', 'g', array['C10', 'decanoic acid', 'caprinezuur', 'decaanzuur']::text[]),
  ('Caprylic Acid', 'macronutrient', 'g', array['C8', 'octanoic acid', 'caprylzuur', 'octaanzuur']::text[]),
  ('Carbohydrate', 'macronutrient', 'g', array['carbs', 'carbohydrates', 'koolhydraten', 'Total Carbohydrate', 'total carbs', 'totale koolhydraten']::text[]),
  ('Casein', 'macronutrient', 'g', array['milk casein', 'micellar casein', 'caseïne']::text[]),
  ('Cellulose', 'macronutrient', 'g', array['microcrystalline cellulose', 'plant fiber']::text[]),
  ('Cholesterol', 'macronutrient', 'mg', array['dietary cholesterol']::text[]),
  ('Collagen', 'macronutrient', 'g', array['collageen', 'collagen peptides', 'hydrolyzed collagen', 'collagen hydrolysate', 'collageenpeptiden', 'gehydrolyseerd collageen']::text[]),
  ('Conjugated Linoleic Acid', 'macronutrient', 'mg', array['cla', 'geconjugeerd linolzuur']::text[]),
  ('Dietary Fiber', 'macronutrient', 'g', array['fiber', 'fibre', 'vezels', 'voedingsvezels', 'dietary fibre', 'voedingsvezel']::text[]),
  ('Docosahexaenoic Acid', 'macronutrient', 'mg', array['dha', 'omega-3 DHA', 'docosahexaeenzuur']::text[]),
  ('Eicosapentaenoic Acid', 'macronutrient', 'mg', array['epa', 'omega-3 EPA', 'eicosapentaeenzuur']::text[]),
  ('Fat', 'macronutrient', 'g', array['total fat', 'vet', 'vetten', 'fats', 'lipid', 'totaal vet']::text[]),
  ('Fructooligosaccharides', 'macronutrient', 'g', array['FOS', 'oligofructose', 'fructo-oligosachariden']::text[]),
  ('Fructose', 'macronutrient', 'g', array['fruit sugar', 'vruchtensuiker']::text[]),
  ('Galactooligosaccharides', 'macronutrient', 'g', array['GOS', 'galacto-oligosaccharides', 'galacto-oligosachariden']::text[]),
  ('Galactose', 'macronutrient', 'g', array[]::text[]),
  ('Gamma-Linolenic Acid', 'macronutrient', 'mg', array['gla']::text[]),
  ('Glucose', 'macronutrient', 'g', array['dextrose', 'blood sugar', 'druivensuiker']::text[]),
  ('Guar Gum', 'macronutrient', 'g', array['guaran', 'E412', 'guargom']::text[]),
  ('Insoluble Fiber', 'macronutrient', 'g', array['onoplosbare vezels', 'insoluble fibre', 'insoluble dietary fiber']::text[]),
  ('Inulin', 'macronutrient', 'g', array['chicory root fiber', 'fructan', 'inuline']::text[]),
  ('Lactose', 'macronutrient', 'g', array['milk sugar', 'melksuiker']::text[]),
  ('Linoleic Acid', 'macronutrient', 'mg', array['la', 'omega-6 linoleic acid', 'linolzuur']::text[]),
  ('Maltose', 'macronutrient', 'g', array['malt sugar', 'moutsuiker']::text[]),
  ('Medium-Chain Triglycerides', 'macronutrient', 'g', array['mct', 'mct oil', 'mct-olie', 'middellange-keten triglyceriden']::text[]),
  ('Monounsaturated Fat', 'macronutrient', 'g', array['mufa', 'enkelvoudig onverzadigd vet', 'Monounsaturated Fatty Acids', 'enkelvoudig onverzadigde vetzuren']::text[]),
  ('Oleic Acid', 'macronutrient', 'mg', array['omega-9', 'oliezuur', 'omega-9 oleic acid']::text[]),
  ('Omega-3 Fatty Acids', 'macronutrient', 'mg', array['omega-3 vetzuren', 'n-3 fatty acids', 'omega 3-vetzuren']::text[]),
  ('Omega-6 Fatty Acids', 'macronutrient', 'mg', array['omega-6 vetzuren', 'n-6 fatty acids', 'omega 6-vetzuren']::text[]),
  ('Pectin', 'macronutrient', 'g', array['fruit pectin', 'pectine']::text[]),
  ('Polyunsaturated Fat', 'macronutrient', 'g', array['pufa', 'meervoudig onverzadigd vet', 'Polyunsaturated Fatty Acids', 'meervoudig onverzadigde vetzuren']::text[]),
  ('Protein', 'macronutrient', 'g', array['proteins', 'eiwit', 'eiwitten', 'proteïne', 'amino acid total']::text[]),
  ('Psyllium Husk', 'macronutrient', 'g', array['ispaghula husk', 'Plantago ovata husk', 'psylliumvezels', 'vlozaadvezels']::text[]),
  ('Resistant Starch', 'macronutrient', 'g', array['RS', 'resistant carbohydrate', 'resistent zetmeel']::text[]),
  ('Saturated Fat', 'macronutrient', 'g', array['saturated fatty acids', 'verzadigd vet', 'saturates', 'SFA', 'verzadigde vetzuren']::text[]),
  ('Soluble Fiber', 'macronutrient', 'g', array['oplosbare vezels', 'soluble fibre', 'soluble dietary fiber']::text[]),
  ('Starch', 'macronutrient', 'g', array['polysaccharide', 'zetmeel', 'complex carbohydrate']::text[]),
  ('Sucrose', 'macronutrient', 'g', array['table sugar', 'saccharose']::text[]),
  ('Sugar', 'macronutrient', 'g', array['total sugars', 'suiker', 'suikers', 'sugars', 'total sugar', 'totale suikers']::text[]),
  ('Trans Fat', 'macronutrient', 'g', array['trans fatty acids', 'transvet', 'trans-fat', 'transvetzuren']::text[]),
  ('Whey Protein Isolate', 'macronutrient', 'g', array['whey isolate', 'WPI', 'wei-eiwit isolaat']::text[]),
  ('Xanthan Gum', 'macronutrient', 'g', array['xanthan', 'E415', 'xanthaangom']::text[]),
  ('Amlodipine', 'medication', 'mg', array[]::text[]),
  ('Amoxicillin', 'medication', 'mg', array['amoxicilline']::text[]),
  ('Aspirin', 'medication', 'mg', array['acetylsalicylic acid', 'acetylsalicylzuur', 'aspirine']::text[]),
  ('Atomoxetine', 'medication', 'mg', array['Strattera']::text[]),
  ('Atorvastatin', 'medication', 'mg', array['lipitor', 'atorvastatine']::text[]),
  ('Azithromycin', 'medication', 'mg', array['zithromax', 'azitromycine']::text[]),
  ('Bupropion', 'medication', 'mg', array['Wellbutrin', 'Zyban']::text[]),
  ('Cetirizine', 'medication', 'mg', array['zyrtec']::text[]),
  ('Dexamfetamine', 'medication', 'mg', array['dexamphetamine', 'dextroamphetamine', 'Tentin']::text[]),
  ('Diclofenac', 'medication', 'mg', array['voltaren']::text[]),
  ('Diphenhydramine', 'medication', 'mg', array['benadryl', 'difenhydramine', 'sleep aid']::text[]),
  ('Fluoxetine', 'medication', 'mg', array['prozac']::text[]),
  ('Ibuprofen', 'medication', 'mg', array['advil', 'nurofen', 'NSAID']::text[]),
  ('Levothyroxine', 'medication', 'mcg', array['synthroid', 'thyrax']::text[]),
  ('Lisdexamfetamine', 'medication', 'mg', array['Vyvanse', 'Elvanse', 'lisdexamphetamine']::text[]),
  ('Lisinopril', 'medication', 'mg', array[]::text[]),
  ('Loperamide', 'medication', 'mg', array['imodium']::text[]),
  ('Loratadine', 'medication', 'mg', array['claritin']::text[]),
  ('Metformin', 'medication', 'mg', array['glucophage', 'metformine']::text[]),
  ('Methylphenidate', 'medication', 'mg', array['ritalin', 'concerta', 'methylfenidaat', 'Medikinet']::text[]),
  ('Metoprolol', 'medication', 'mg', array[]::text[]),
  ('Modafinil', 'medication', 'mg', array['Provigil', 'Modiodal']::text[]),
  ('Naproxen', 'medication', 'mg', array['aleve']::text[]),
  ('Omeprazole', 'medication', 'mg', array['prilosec', 'omeprazol']::text[]),
  ('Paracetamol', 'medication', 'mg', array['acetaminophen', 'tylenol', 'APAP']::text[]),
  ('Prednisone', 'medication', 'mg', array['prednison']::text[]),
  ('Pseudoephedrine', 'medication', 'mg', array['sudafed', 'pseudo-efedrine', 'decongestant']::text[]),
  ('Salbutamol', 'medication', 'mcg', array['albuterol', 'ventolin']::text[]),
  ('Sertraline', 'medication', 'mg', array['zoloft']::text[]),
  ('Boron', 'mineral', 'mg', array['b', 'boor', 'borium']::text[]),
  ('Calcium', 'mineral', 'mg', array['ca', 'calcium ion', 'kalk']::text[]),
  ('Chromium', 'mineral', 'mcg', array['cr', 'chroom']::text[]),
  ('Copper', 'mineral', 'mg', array['cu', 'koper', 'cuprum']::text[]),
  ('Fluoride', 'mineral', 'mg', array['f', 'fluor', 'fluorine']::text[]),
  ('Iodine', 'mineral', 'mcg', array['i', 'iodide', 'jodium', 'jood', 'jodide']::text[]),
  ('Iron', 'mineral', 'mg', array['fe', 'ijzer', 'ferrum']::text[]),
  ('Magnesium', 'mineral', 'mg', array['mg', 'magnesium ion']::text[]),
  ('Manganese', 'mineral', 'mg', array['mn', 'mangaan']::text[]),
  ('Molybdenum', 'mineral', 'mcg', array['mo', 'molybdeen']::text[]),
  ('Phosphorus', 'mineral', 'mg', array['p', 'phosphate', 'fosfor', 'fosfaat']::text[]),
  ('Selenium', 'mineral', 'mcg', array['se']::text[]),
  ('Silicon', 'mineral', 'mg', array['si', 'silica', 'silicium']::text[]),
  ('Zinc', 'mineral', 'mg', array['zn', 'zink']::text[]),
  ('Zinc Picolinate', 'mineral', 'mg', array['zinkpicolinaat']::text[]),
  ('Acesulfame K', 'other', 'mg', array['acesulfame potassium', 'e950', 'acesulfaam-k']::text[]),
  ('Acetic Acid', 'other', 'mg', array['vinegar acid', 'acetate', 'azijnzuur', 'acetaat']::text[]),
  ('Allium Sativum', 'other', 'mg', array['garlic', 'knoflook', 'Garlic Extract', 'Allium sativum extract', 'aged garlic extract', 'knoflookextract']::text[]),
  ('Aspartame', 'other', 'mg', array['e951', 'aspartaam']::text[]),
  ('Bacopa Monnieri', 'other', 'mg', array['bacopa', 'brahmi']::text[]),
  ('Beetroot Extract', 'other', 'mg', array['Beta vulgaris extract', 'beet extract', 'rode bietenextract', 'bietenextract']::text[]),
  ('Bifidobacterium Bifidum', 'other', 'cfu', array['b. bifidum']::text[]),
  ('Bifidobacterium Lactis', 'other', 'cfu', array['B. lactis', 'Bifidobacterium animalis subsp. lactis']::text[]),
  ('Bifidobacterium Longum', 'other', 'cfu', array['b. longum']::text[]),
  ('Camellia Sinensis', 'other', 'mg', array['green tea extract', 'groene thee', 'Camellia sinensis extract', 'tea extract', 'groene thee-extract']::text[]),
  ('Cinnamon Extract', 'other', 'mg', array['Cinnamomum extract', 'kaneelextract']::text[]),
  ('Citric Acid', 'other', 'mg', array['citrate acid', 'E330', 'citroenzuur']::text[]),
  ('Cranberry Extract', 'other', 'mg', array['Vaccinium macrocarpon extract', 'cranberry-extract', 'veenbesextract']::text[]),
  ('Curcuma Longa', 'other', 'mg', array['turmeric', 'kurkuma', 'Curcuma longa extract', 'turmeric root extract', 'kurkuma-extract', 'geelwortel']::text[]),
  ('Echinacea Purpurea', 'other', 'mg', array['echinacea', 'rode zonnehoed']::text[]),
  ('Erythritol', 'other', 'g', array['erytritol', 'sugar alcohol', 'E968']::text[]),
  ('Ginkgo Biloba', 'other', 'mg', array['ginkgo', 'ginkgo biloba extract', 'ginkgo extract', 'maidenhair tree extract', 'ginkgo biloba-extract']::text[]),
  ('Grape Seed Extract', 'other', 'mg', array['Vitis vinifera extract', 'OPC extract', 'druivenpitextract']::text[]),
  ('Griffonia Simplicifolia', 'other', 'mg', array['griffonia', 'griffonia-extract', 'Griffonia Seed Extract', 'Griffonia simplicifolia extract', '5-HTP source']::text[]),
  ('Humulus Lupulus', 'other', 'mg', array['hops', 'hop', 'Hop Extract', 'Humulus lupulus extract', 'hops extract', 'hopextract']::text[]),
  ('Hypericum Perforatum', 'other', 'mg', array['st johns wort', 'sint-janskruid']::text[]),
  ('Lactic Acid', 'other', 'mg', array['lactate', 'E270', 'melkzuur', 'lactaat']::text[]),
  ('Lactobacillus Acidophilus', 'other', 'cfu', array['l. acidophilus', 'acidophilus']::text[]),
  ('Lactobacillus Rhamnosus', 'other', 'cfu', array['lgg', 'l. rhamnosus']::text[]),
  ('Lavandula Angustifolia', 'other', 'mg', array['lavender', 'lavendel']::text[]),
  ('Lepidium Meyenii', 'other', 'mg', array['maca', 'maca-extract', 'Maca Extract', 'Lepidium meyenii extract', 'Peruvian ginseng']::text[]),
  ('Malic Acid', 'other', 'mg', array['malate', 'apple acid', 'appelzuur', 'malaat']::text[]),
  ('Maltitol', 'other', 'g', array['e965']::text[]),
  ('Matricaria Chamomilla', 'other', 'mg', array['chamomile', 'kamille']::text[]),
  ('Melissa Officinalis', 'other', 'mg', array['lemon balm', 'citroenmelisse', 'Lemon Balm Extract', 'Melissa officinalis extract', 'melissa', 'citroenmelisse-extract']::text[]),
  ('Monosodium Glutamate', 'other', 'mg', array['MSG', 'E621', 'sodium glutamate', 'mononatriumglutamaat', 've-tsin']::text[]),
  ('Panax Ginseng', 'other', 'mg', array['korean ginseng', 'ginseng', 'panax ginseng extract', 'Asian ginseng', 'Panax ginseng-extract']::text[]),
  ('Passiflora Incarnata', 'other', 'mg', array['passionflower', 'passiebloem', 'Passionflower Extract', 'Passiflora incarnata extract', 'passiebloemextract']::text[]),
  ('Potassium Sorbate', 'other', 'mg', array['E202', 'kaliumsorbaat']::text[]),
  ('Probiotics', 'other', 'cfu', array['probiotica', 'live cultures', 'probiotic blend', 'levende culturen']::text[]),
  ('Rhodiola Rosea', 'other', 'mg', array['rhodiola', 'golden root', 'rozenwortel', 'Rhodiola Rosea Extract', 'roseroot extract', 'rozenwortel-extract']::text[]),
  ('Saccharomyces Boulardii', 'other', 'cfu', array['s. boulardii', 'probiotic yeast']::text[]),
  ('Saw Palmetto Extract', 'other', 'mg', array['Serenoa repens extract', 'zaagpalmextract', 'saw palmetto']::text[]),
  ('Silybum Marianum', 'other', 'mg', array['milk thistle', 'mariadistel', 'Milk Thistle Extract', 'Silybum marianum extract', 'mariadistel-extract']::text[]),
  ('Sodium Benzoate', 'other', 'mg', array['E211', 'natriumbenzoaat']::text[]),
  ('Sorbitol', 'other', 'g', array['e420']::text[]),
  ('Soy Lecithin', 'other', 'mg', array['lecithin', 'E322', 'sojalecithine', 'lecithine']::text[]),
  ('Steviol Glycosides', 'other', 'mg', array['stevia', 'stevia extract', 'E960', 'steviolglycosiden']::text[]),
  ('Sucralose', 'other', 'mg', array['e955', 'Splenda']::text[]),
  ('Valeriana Officinalis', 'other', 'mg', array['valerian', 'valeriaan', 'Valerian Root Extract', 'Valeriana officinalis extract', 'valeriaanextract', 'valeriaanwortel']::text[]),
  ('Withania Somnifera', 'other', 'mg', array['ashwagandha', 'winter cherry', 'ashwagandha-extract', 'Ashwagandha Extract', 'Withania somnifera extract', 'Indian ginseng']::text[]),
  ('Xylitol', 'other', 'g', array['birch sugar', 'E967', 'berkensuiker']::text[]),
  ('Zingiber Officinale', 'other', 'mg', array['ginger', 'gember', 'Ginger Extract', 'Zingiber officinale extract', 'gemberextract']::text[]),
  ('Cannabidiol', 'psychoactive', 'mg', array['cbd']::text[]),
  ('Ethanol', 'psychoactive', 'g', array['alcohol', 'ethyl alcohol', 'ethylalcohol', 'booze']::text[]),
  ('Kava', 'psychoactive', 'mg', array['piper methysticum', 'kavakava']::text[]),
  ('Kratom', 'psychoactive', 'mg', array['mitragyna speciosa']::text[]),
  ('MDMA', 'psychoactive', 'mg', array['ecstasy']::text[]),
  ('Nitrous Oxide', 'psychoactive', 'ml', array['laughing gas', 'lachgas', 'n2o']::text[]),
  ('Psilocybin', 'psychoactive', 'mg', array['psilocybine']::text[]),
  ('Tetrahydrocannabinol', 'psychoactive', 'mg', array['thc']::text[]),
  ('Caffeine', 'stimulant', 'mg', array['cafeïne', '1,3,7-trimethylxanthine', 'coffee caffeine']::text[]),
  ('Guarana', 'stimulant', 'mg', array['paullinia cupana']::text[]),
  ('Nicotine', 'stimulant', 'mg', array[]::text[]),
  ('Synephrine', 'stimulant', 'mg', array['bitter orange', 'synefrine']::text[]),
  ('Theobromine', 'stimulant', 'mg', array['cocoa alkaloid', '3,7-dimethylxanthine']::text[]),
  ('Theophylline', 'stimulant', 'mg', array['theofylline', '1,3-dimethylxanthine', 'tea alkaloid']::text[]),
  ('Yohimbine', 'stimulant', 'mg', array['yohimbe']::text[]),
  ('5-Hydroxytryptophan', 'supplement_compound', 'mg', array['5-htp', 'oxitriptan', '5-hydroxytryptofaan']::text[]),
  ('Acetyl-L-Carnitine Hydrochloride', 'supplement_compound', 'mg', array['ALCAR HCl', 'acetyl carnitine']::text[]),
  ('Alanine', 'supplement_compound', 'g', array['L-alanine']::text[]),
  ('Alpha-Lipoic Acid', 'supplement_compound', 'mg', array['lipoic acid', 'alfa-liponzuur', 'thioctic acid']::text[]),
  ('Anthocyanins', 'supplement_compound', 'mg', array['anthocyanen']::text[]),
  ('Arginine', 'supplement_compound', 'mg', array['l-arginine']::text[]),
  ('Arginine Alpha-Ketoglutarate', 'supplement_compound', 'g', array['AAKG', 'arginine AKG', 'arginine alfa-ketoglutaraat']::text[]),
  ('Berberine', 'supplement_compound', 'mg', array['berberine hydrochloride', 'berberine HCl']::text[]),
  ('Beta-Alanine', 'supplement_compound', 'g', array['β-alanine', 'bèta-alanine', 'beta alanine']::text[]),
  ('Betaine', 'supplement_compound', 'mg', array['trimethylglycine', 'tmg', 'betaïne']::text[]),
  ('Bioflavonoids', 'supplement_compound', 'mg', array['citrus bioflavonoids', 'bioflavonoïden']::text[]),
  ('Branched-Chain Amino Acids', 'supplement_compound', 'g', array['BCAAs', 'leucine isoleucine valine', 'vertakte-keten aminozuren', 'BCAA''s']::text[]),
  ('Catechin', 'supplement_compound', 'mg', array['catechine']::text[]),
  ('Chlorogenic Acid', 'supplement_compound', 'mg', array['chlorogeenzuur', 'green coffee extract']::text[]),
  ('Chondroitin', 'supplement_compound', 'mg', array['chondroitin sulfate', 'chondroïtine', 'chondroitin sulphate', 'chondroïtinesulfaat']::text[]),
  ('Citrulline Malate', 'supplement_compound', 'g', array['L-citrulline malate', 'citrulline malaat']::text[]),
  ('Creatine', 'supplement_compound', 'g', array['creatine base']::text[]),
  ('Creatine Monohydrate', 'supplement_compound', 'g', array['creatine-monohydraat', 'creatine mono', 'creatine monohydraat']::text[]),
  ('Curcumin', 'supplement_compound', 'mg', array['curcumine', 'curcuminoids', 'turmeric polyphenol']::text[]),
  ('Cysteine', 'supplement_compound', 'mg', array['l-cysteine', 'cysteïne']::text[]),
  ('DHEA', 'supplement_compound', 'mg', array['dehydroepiandrosterone']::text[]),
  ('Epigallocatechin Gallate', 'supplement_compound', 'mg', array['egcg', 'green tea catechin', 'epigallocatechinegallaat']::text[]),
  ('Essential Amino Acids', 'supplement_compound', 'g', array['EAAs', 'indispensable amino acids', 'essentiële aminozuren']::text[]),
  ('Fish Oil', 'supplement_compound', 'mg', array['fish oil triglyceride', 'omega-3 fish oil']::text[]),
  ('Gamma-Aminobutyric Acid', 'supplement_compound', 'mg', array['gaba', 'gamma aminobutyric acid', 'gamma-aminoboterzuur']::text[]),
  ('Glucosamine', 'supplement_compound', 'mg', array['Glucosamine Sulfate', 'glucosamine sulphate', 'glucosaminesulfaat']::text[]),
  ('Glutamine', 'supplement_compound', 'g', array['l-glutamine']::text[]),
  ('Glutathione', 'supplement_compound', 'mg', array['gsh', 'glutathion']::text[]),
  ('Glycine', 'supplement_compound', 'g', array['l-glycine']::text[]),
  ('Hesperidin', 'supplement_compound', 'mg', array['hesperidine']::text[]),
  ('Histidine', 'supplement_compound', 'mg', array['l-histidine']::text[]),
  ('Hyaluronic Acid', 'supplement_compound', 'mg', array['hyaluronzuur', 'sodium hyaluronate', 'hyaluronan']::text[]),
  ('Isoleucine', 'supplement_compound', 'mg', array['l-isoleucine', 'BCAA isoleucine']::text[]),
  ('Krill Oil', 'supplement_compound', 'mg', array['Antarctic krill oil', 'phospholipid omega-3', 'krillolie']::text[]),
  ('L-Carnitine', 'supplement_compound', 'mg', array['carnitine', 'acetyl-l-carnitine', 'alcar', 'levocarnitine']::text[]),
  ('L-Citrulline', 'supplement_compound', 'g', array['citrulline']::text[]),
  ('L-Ornithine', 'supplement_compound', 'mg', array['ornithine']::text[]),
  ('L-Theanine', 'supplement_compound', 'mg', array['theanine', 'l-theanin']::text[]),
  ('Leucine', 'supplement_compound', 'mg', array['l-leucine', 'BCAA leucine']::text[]),
  ('Lysine', 'supplement_compound', 'mg', array['l-lysine']::text[]),
  ('Melatonin', 'supplement_compound', 'mg', array['melatonine', 'N-acetyl-5-methoxytryptamine', 'sleep hormone']::text[]),
  ('Methionine', 'supplement_compound', 'mg', array['l-methionine']::text[]),
  ('Methylsulfonylmethane', 'supplement_compound', 'g', array['msm', 'methylsulfonylmethaan', 'dimethyl sulfone']::text[]),
  ('N-Acetyl-L-Tyrosine', 'supplement_compound', 'mg', array['NALT', 'acetyl tyrosine']::text[]),
  ('N-Acetylcysteine', 'supplement_compound', 'mg', array['nac', 'n-acetylcysteïne', 'acetylcysteine', 'acetylcysteïne']::text[]),
  ('Naringin', 'supplement_compound', 'mg', array['naringine']::text[]),
  ('Nicotinamide Mononucleotide', 'supplement_compound', 'mg', array['nmn', 'beta-NMN', 'nicotinamide-mononucleotide']::text[]),
  ('Nicotinamide Riboside', 'supplement_compound', 'mg', array['nr', 'niagen', 'nicotinamide-riboside']::text[]),
  ('Nitrate', 'supplement_compound', 'mg', array['NO3', 'dietary nitrate', 'beet nitrate', 'nitraat']::text[]),
  ('Phenylalanine', 'supplement_compound', 'mg', array['l-phenylalanine', 'fenylalanine']::text[]),
  ('Phosphatidylserine', 'supplement_compound', 'mg', array['ps', 'fosfatidylserine']::text[]),
  ('Piperine', 'supplement_compound', 'mg', array['black pepper extract', 'BioPerine', 'zwarte peper-extract']::text[]),
  ('Pregnenolone', 'supplement_compound', 'mg', array['pregnenolon']::text[]),
  ('Proanthocyanidins', 'supplement_compound', 'mg', array['opc', 'pycnogenol', 'procyanidins']::text[]),
  ('Proline', 'supplement_compound', 'g', array['L-proline']::text[]),
  ('Quercetin', 'supplement_compound', 'mg', array['quercetine', 'flavonoid']::text[]),
  ('Resveratrol', 'supplement_compound', 'mg', array['trans-resveratrol', 'grape polyphenol']::text[]),
  ('Rutin', 'supplement_compound', 'mg', array['rutoside', 'rutine']::text[]),
  ('Serine', 'supplement_compound', 'g', array['L-serine']::text[]),
  ('Silymarin', 'supplement_compound', 'mg', array['milk thistle flavonolignans', 'silymarine']::text[]),
  ('Sodium Bicarbonate', 'supplement_compound', 'g', array['bicarbonate of soda', 'natriumbicarbonaat', 'zuiveringszout']::text[]),
  ('Taurine', 'supplement_compound', 'mg', array['2-aminoethanesulfonic acid']::text[]),
  ('Threonine', 'supplement_compound', 'mg', array['l-threonine']::text[]),
  ('Tryptophan', 'supplement_compound', 'mg', array['l-tryptophan', 'tryptofaan']::text[]),
  ('Tyrosine', 'supplement_compound', 'mg', array['l-tyrosine']::text[]),
  ('Ubiquinone', 'supplement_compound', 'mg', array['coenzyme q10', 'coq10', 'ubiquinol', 'co-enzym q10', 'ubiquinon']::text[]),
  ('Valine', 'supplement_compound', 'mg', array['l-valine', 'BCAA valine']::text[]),
  ('4-Aminobenzoic Acid', 'vitamin', 'mg', array['paba', 'para-aminobenzoic acid', 'vitamin b10', 'para-aminobenzoëzuur']::text[]),
  ('Alpha-Carotene', 'vitamin', 'mg', array['alfa-caroteen']::text[]),
  ('Ascorbic Acid', 'vitamin', 'mg', array['vitamin c', 'vitamine c', 'ascorbinezuur', 'ascorbate']::text[]),
  ('Astaxanthin', 'vitamin', 'mg', array['astaxanthine']::text[]),
  ('Beta-Carotene', 'vitamin', 'mcg', array['provitamin a', 'bèta-caroteen', 'β-carotene', 'bètacaroteen', 'provitamine A']::text[]),
  ('Biotin', 'vitamin', 'mcg', array['vitamin b7', 'vitamin h', 'biotine', 'vitamine b7']::text[]),
  ('Cholecalciferol', 'vitamin', 'mcg', array['vitamin d3', 'vit-d', 'vitamine d (1 mcg = 40 IU)', 'colecalciferol', 'vitamine D3']::text[]),
  ('Choline', 'vitamin', 'mg', array['choline bitartrate', 'vitamin b4', 'CDP-choline']::text[]),
  ('Cobalamin', 'vitamin', 'mcg', array['vitamin b12', 'vitamine b12', 'cobalamins', 'cobalamine']::text[]),
  ('Cyanocobalamin', 'vitamin', 'mcg', array['vitamin B12 cyanocobalamin', 'cyanocobalamine']::text[]),
  ('Ergocalciferol', 'vitamin', 'mcg', array['vitamin d2', 'vitamine d2']::text[]),
  ('Folate', 'vitamin', 'mcg', array['vitamin b9', 'folaat', 'folacin', 'vitamine B9']::text[]),
  ('Folic Acid', 'vitamin', 'mcg', array['pteroylmonoglutamic acid', 'synthetic folate']::text[]),
  ('Inositol', 'vitamin', 'mg', array['myo-inositol', 'vitamin b8']::text[]),
  ('Levomefolic Acid', 'vitamin', 'mcg', array['5-MTHF', 'L-methylfolate', 'methylfolate', 'methylfolaat']::text[]),
  ('Lutein', 'vitamin', 'mg', array['luteïne']::text[]),
  ('Lycopene', 'vitamin', 'mg', array['lycopeen']::text[]),
  ('Menaquinone', 'vitamin', 'mcg', array['vitamin k2', 'mk-7', 'vitamine k2', 'Menaquinone-7', 'vitamin K2 MK-7', 'vitamine K2 MK-7', 'menachinon-7']::text[]),
  ('Methylcobalamin', 'vitamin', 'mcg', array['methyl-B12', 'vitamin B12 methylcobalamin', 'methylcobalamine']::text[]),
  ('Mixed Tocopherols', 'vitamin', 'mg', array['mixed vitamin E', 'tocopherol mix', 'gemengde tocoferolen']::text[]),
  ('Niacin', 'vitamin', 'mg', array['vitamin b3', 'nicotinic acid', 'niacine', 'vitamine b3', 'nicotinezuur']::text[]),
  ('Nicotinamide', 'vitamin', 'mg', array['niacinamide', 'vitamin B3 amide']::text[]),
  ('Pantothenic Acid', 'vitamin', 'mg', array['vitamin b5', 'pantotheenzuur', 'vitamine b5', 'pantothenate']::text[]),
  ('Phylloquinone', 'vitamin', 'mcg', array['vitamin k1', 'phytonadione', 'vitamine k1', 'fyllochinon']::text[]),
  ('Pyridoxal 5''-Phosphate', 'vitamin', 'mg', array['P5P', 'active vitamin B6', 'pyridoxaal-5-fosfaat', 'actieve vitamine B6']::text[]),
  ('Pyridoxine', 'vitamin', 'mg', array['vitamin b6', 'vitamine b6', 'pyridoxine hydrochloride']::text[]),
  ('Retinol', 'vitamin', 'mcg', array['retinyl palmitate', 'preformed vitamin A', 'vitamin A1', 'vitamine A1']::text[]),
  ('Riboflavin', 'vitamin', 'mg', array['vitamin b2', 'vitamine b2', 'riboflavine']::text[]),
  ('Thiamine', 'vitamin', 'mg', array['vitamin b1', 'thiamin', 'vitamine b1']::text[]),
  ('Tocopherol', 'vitamin', 'mg', array['alpha-tocopherol', 'α-tocopherol', 'd-alpha tocopherol', 'alfa-tocoferol']::text[]),
  ('Vitamin A', 'vitamin', 'mcg', array['retinoids', 'vitamin A activity']::text[]),
  ('Vitamin D', 'vitamin', 'mcg', array['calciferol', 'vitamin D total', 'vitamine D']::text[]),
  ('Vitamin E', 'vitamin', 'mg', array['tocopherols', 'vitamin E activity']::text[]),
  ('Vitamin K', 'vitamin', 'mcg', array['vitamin K total', 'vitamine K']::text[]),
  ('Zeaxanthin', 'vitamin', 'mg', array['zeaxanthine']::text[]),
  ('Water', 'water', 'ml', array['h2o', 'aqua', 'moisture', 'fluid', 'vocht']::text[])
on conflict (name) do update set
  substance_type = excluded.substance_type,
  canonical_unit = excluded.canonical_unit,
  aliases        = excluded.aliases;

-- Drop legacy substances not in the catalog that nothing points at. On a fresh DB this
-- clears the original 0002 seed; on QA (all legacy rows referenced) it deletes nothing.
delete from substance
 where name not in ('Bicarbonate', 'Chloride', 'Magnesium Citrate', 'Magnesium Glycinate', 'Potassium', 'Potassium Citrate', 'Sodium', 'Sodium Chloride', 'Energy', 'Added Sugars', 'Alpha-Linolenic Acid', 'Arachidonic Acid', 'Beta-Glucan', 'Capric Acid', 'Caprylic Acid', 'Carbohydrate', 'Casein', 'Cellulose', 'Cholesterol', 'Collagen', 'Conjugated Linoleic Acid', 'Dietary Fiber', 'Docosahexaenoic Acid', 'Eicosapentaenoic Acid', 'Fat', 'Fructooligosaccharides', 'Fructose', 'Galactooligosaccharides', 'Galactose', 'Gamma-Linolenic Acid', 'Glucose', 'Guar Gum', 'Insoluble Fiber', 'Inulin', 'Lactose', 'Linoleic Acid', 'Maltose', 'Medium-Chain Triglycerides', 'Monounsaturated Fat', 'Oleic Acid', 'Omega-3 Fatty Acids', 'Omega-6 Fatty Acids', 'Pectin', 'Polyunsaturated Fat', 'Protein', 'Psyllium Husk', 'Resistant Starch', 'Saturated Fat', 'Soluble Fiber', 'Starch', 'Sucrose', 'Sugar', 'Trans Fat', 'Whey Protein Isolate', 'Xanthan Gum', 'Amlodipine', 'Amoxicillin', 'Aspirin', 'Atomoxetine', 'Atorvastatin', 'Azithromycin', 'Bupropion', 'Cetirizine', 'Dexamfetamine', 'Diclofenac', 'Diphenhydramine', 'Fluoxetine', 'Ibuprofen', 'Levothyroxine', 'Lisdexamfetamine', 'Lisinopril', 'Loperamide', 'Loratadine', 'Metformin', 'Methylphenidate', 'Metoprolol', 'Modafinil', 'Naproxen', 'Omeprazole', 'Paracetamol', 'Prednisone', 'Pseudoephedrine', 'Salbutamol', 'Sertraline', 'Boron', 'Calcium', 'Chromium', 'Copper', 'Fluoride', 'Iodine', 'Iron', 'Magnesium', 'Manganese', 'Molybdenum', 'Phosphorus', 'Selenium', 'Silicon', 'Zinc', 'Zinc Picolinate', 'Acesulfame K', 'Acetic Acid', 'Allium Sativum', 'Aspartame', 'Bacopa Monnieri', 'Beetroot Extract', 'Bifidobacterium Bifidum', 'Bifidobacterium Lactis', 'Bifidobacterium Longum', 'Camellia Sinensis', 'Cinnamon Extract', 'Citric Acid', 'Cranberry Extract', 'Curcuma Longa', 'Echinacea Purpurea', 'Erythritol', 'Ginkgo Biloba', 'Grape Seed Extract', 'Griffonia Simplicifolia', 'Humulus Lupulus', 'Hypericum Perforatum', 'Lactic Acid', 'Lactobacillus Acidophilus', 'Lactobacillus Rhamnosus', 'Lavandula Angustifolia', 'Lepidium Meyenii', 'Malic Acid', 'Maltitol', 'Matricaria Chamomilla', 'Melissa Officinalis', 'Monosodium Glutamate', 'Panax Ginseng', 'Passiflora Incarnata', 'Potassium Sorbate', 'Probiotics', 'Rhodiola Rosea', 'Saccharomyces Boulardii', 'Saw Palmetto Extract', 'Silybum Marianum', 'Sodium Benzoate', 'Sorbitol', 'Soy Lecithin', 'Steviol Glycosides', 'Sucralose', 'Valeriana Officinalis', 'Withania Somnifera', 'Xylitol', 'Zingiber Officinale', 'Cannabidiol', 'Ethanol', 'Kava', 'Kratom', 'MDMA', 'Nitrous Oxide', 'Psilocybin', 'Tetrahydrocannabinol', 'Caffeine', 'Guarana', 'Nicotine', 'Synephrine', 'Theobromine', 'Theophylline', 'Yohimbine', '5-Hydroxytryptophan', 'Acetyl-L-Carnitine Hydrochloride', 'Alanine', 'Alpha-Lipoic Acid', 'Anthocyanins', 'Arginine', 'Arginine Alpha-Ketoglutarate', 'Berberine', 'Beta-Alanine', 'Betaine', 'Bioflavonoids', 'Branched-Chain Amino Acids', 'Catechin', 'Chlorogenic Acid', 'Chondroitin', 'Citrulline Malate', 'Creatine', 'Creatine Monohydrate', 'Curcumin', 'Cysteine', 'DHEA', 'Epigallocatechin Gallate', 'Essential Amino Acids', 'Fish Oil', 'Gamma-Aminobutyric Acid', 'Glucosamine', 'Glutamine', 'Glutathione', 'Glycine', 'Hesperidin', 'Histidine', 'Hyaluronic Acid', 'Isoleucine', 'Krill Oil', 'L-Carnitine', 'L-Citrulline', 'L-Ornithine', 'L-Theanine', 'Leucine', 'Lysine', 'Melatonin', 'Methionine', 'Methylsulfonylmethane', 'N-Acetyl-L-Tyrosine', 'N-Acetylcysteine', 'Naringin', 'Nicotinamide Mononucleotide', 'Nicotinamide Riboside', 'Nitrate', 'Phenylalanine', 'Phosphatidylserine', 'Piperine', 'Pregnenolone', 'Proanthocyanidins', 'Proline', 'Quercetin', 'Resveratrol', 'Rutin', 'Serine', 'Silymarin', 'Sodium Bicarbonate', 'Taurine', 'Threonine', 'Tryptophan', 'Tyrosine', 'Ubiquinone', 'Valine', '4-Aminobenzoic Acid', 'Alpha-Carotene', 'Ascorbic Acid', 'Astaxanthin', 'Beta-Carotene', 'Biotin', 'Cholecalciferol', 'Choline', 'Cobalamin', 'Cyanocobalamin', 'Ergocalciferol', 'Folate', 'Folic Acid', 'Inositol', 'Levomefolic Acid', 'Lutein', 'Lycopene', 'Menaquinone', 'Methylcobalamin', 'Mixed Tocopherols', 'Niacin', 'Nicotinamide', 'Pantothenic Acid', 'Phylloquinone', 'Pyridoxal 5''-Phosphate', 'Pyridoxine', 'Retinol', 'Riboflavin', 'Thiamine', 'Tocopherol', 'Vitamin A', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Zeaxanthin', 'Water')
   and id not in (select substance_id from item_component where substance_id is not null)
   and id not in (select substance_id from resolved_amount);
